version: '3.3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=hospital
      - MONGO_DATA_DIR=/data/mongo/db
    volumes:
      - ./docker/compose/data/mongo/db:/data/db
      - ./docker/compose/conf/mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
#    command: mongod --smallfiles --logpath=/dev/null # --quiet
  hospital_app:
    image: sshishov/hospital_app:latest
    container_name: hospital_app
    ports:
      - 8013:8000
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb
    env_file:
      - ./docker/compose/envs/hospital_app.env
