# Generated by Django 2.0.5 on 2018-06-06 18:05

from __future__ import unicode_literals
from django.db import migrations


def append_perms_and_groups(apps, schema_editor):
    # Get models that we needs them
    users_model = apps.get_model("auth", "User")
    permissions_model = apps.get_model("auth", "Permission")
    groups_model = apps.get_model("auth", "Group")
    content_type = apps.get_model("contenttypes", "ContentType")

    # Get user content type object
    uct = content_type.objects.get_for_model(users_model)
    db_alias = schema_editor.connection.alias

    # Append custom permissions
    can_add_patients_perm = permissions_model.objects.create(codename='can_add_patients',
                          name='Can add patients',
                          content_type=uct)
    can_view_all_apps_perm = permissions_model.objects.create(codename='can_view_all_apps',
                          name='Can view all applications per project',
                          content_type=uct)
    can_manage_apps_perm = permissions_model.objects.create(codename='can_manage_apps',
                          name='Can manage applications',
                          content_type=uct)
    can_add_apps_perm = permissions_model.objects.create(codename='can_add_apps',
                          name='Can add applications',
                          content_type=uct)

    # Get necessary permissions for group creation
    # NOTE: !!! We can't get predefined permissions here.
    # Predefined permissions are unavailable in db for this step

    # Groups Creation
    supervisors_group = groups_model.objects.create(name='Supervisors')
    doctors_group = groups_model.objects.create(name='Doctors')

    # Append specific permissions to created groups
    # supervisors_group.permissions.add(can_view_all_apps_perm)
    supervisors_group.permissions.set([can_view_all_apps_perm,
                                       can_manage_apps_perm,
                                       can_add_apps_perm,
                                       can_add_patients_perm])

    doctors_group.permissions.set([can_manage_apps_perm,
                                   can_add_apps_perm,
                                   can_add_patients_perm])


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            append_perms_and_groups,
        ),
    ]
